//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public int actPID { get; set; }
        public string actName { get; set; }
        public string actDescription { get; set; }
        public Nullable<int> actDuration { get; set; }
        public Nullable<double> actCost { get; set; }
        public Nullable<int> actStudyArmLinkID { get; set; }
    }
}
