//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int appPID { get; set; }
        public Nullable<System.DateTime> appStartDate { get; set; }
        public Nullable<System.DateTime> appEndDate { get; set; }
        public Nullable<int> appCompletedStatus { get; set; }
        public Nullable<int> appStudyArmLinkID { get; set; }
        public Nullable<int> appActivityLinkID { get; set; }
        public Nullable<int> appVisitLinkID { get; set; }
        public Nullable<int> appDoctorLinkID { get; set; }
        public Nullable<int> appSubjectLinkID { get; set; }
    }
}
