//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public int docPID { get; set; }
        public string docName { get; set; }
        public string docSpecialization { get; set; }
        public string docPhoneNumber { get; set; }
    }
}
