//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentInfo
    {
        public int dinPID { get; set; }
        public string dinDescription { get; set; }
        public string dinFileName { get; set; }
        public byte[] dinBLOB { get; set; }
        public Nullable<int> dinVersion { get; set; }
        public Nullable<int> dinStudyArmLinkID { get; set; }
    }
}
