//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyArm
    {
        public int sarPID { get; set; }
        public string sarName { get; set; }
        public Nullable<int> sarStudyLinkID { get; set; }
        public Nullable<int> sarEnrollmentGoal { get; set; }
    }
}
