//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public int stuPID { get; set; }
        public string stuName { get; set; }
        public string stuDescription { get; set; }
        public Nullable<int> stuEnrollmentGoal { get; set; }
        public string stuCompletedStatus { get; set; }
        public Nullable<System.DateTime> stuStartDate { get; set; }
        public Nullable<System.DateTime> stuEndDate { get; set; }
        public Nullable<int> stuSponsorLinKID { get; set; }
        public Nullable<int> stuSiteLinkID { get; set; }
    }
}
