//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public int subPID { get; set; }
        public string subInitials { get; set; }
        public Nullable<System.DateTime> subDOB { get; set; }
        public string subGender { get; set; }
        public Nullable<double> subHeight { get; set; }
        public string subBloodType { get; set; }
        public string subStatus { get; set; }
        public string subSurvivalStatus { get; set; }
    }
}
