//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectAssignedTo
    {
        public int satPID { get; set; }
        public Nullable<System.DateTime> satCreatedDate { get; set; }
        public string satCreatedBy { get; set; }
        public Nullable<int> satSubjectLinkID { get; set; }
        public Nullable<int> satStudyArmLinkID { get; set; }
    }
}
