//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPermissions
    {
        public int upePID { get; set; }
        public Nullable<System.DateTime> upeCreatedDate { get; set; }
        public string upeCreatedBy { get; set; }
        public Nullable<int> upeUserLinkID { get; set; }
        public Nullable<int> upeStudyLinkID { get; set; }
    }
}
