//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSI_GUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visit
    {
        public int visPID { get; set; }
        public Nullable<int> visName { get; set; }
        public string visDescription { get; set; }
        public Nullable<System.DateTime> visStart { get; set; }
        public Nullable<System.DateTime> visEnd { get; set; }
        public Nullable<int> visStudyArmLinkID { get; set; }
    }
}
